# Generated by Django 5.0.6 on 2024-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='vehiclename',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
