# Generated by Django 5.0.6 on 2024-07-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0002_vehiclemodel_vehiclename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='vhcl_model_name',
        ),
    ]
