# Generated by Django 5.0.6 on 2024-07-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0003_remove_vehiclemodel_vhcl_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
